export const TicTacToeGameABI = [
  {
    type: 'function',
    name: 'createGame',
    inputs: [
      { name: 'opponent', type: 'address' },
      { name: 'wagerAmount', type: 'uint256' },
    ],
    outputs: [{ name: 'gameId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'duelToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'GameCreated',
    inputs: [
      { name: 'gameId', type: 'uint256', indexed: true },
      { name: 'player1', type: 'address', indexed: true },
      { name: 'player2', type: 'address', indexed: true },
      { name: 'wagerAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'getGame',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'player1', type: 'address' },
          { name: 'player2', type: 'address' },
          { name: 'wagerAmount', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'lastMoveAt', type: 'uint256' },
          { name: 'currentTurn', type: 'address' },
          { name: 'winner', type: 'address' },
          { name: 'board', type: 'uint8[9]' },
          { name: 'isDraw', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBoard',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint8[9]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTimeRemaining',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasTimedOut',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'makeMove',
    inputs: [
      { name: 'gameId', type: 'uint256' },
      { name: 'position', type: 'uint8' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimTimeoutWin',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'joinGame',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelGame',
    inputs: [{ name: 'gameId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'MOVE_TIMEOUT',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
